export const INCREMENT_LIKES = 'INCREMENT_LIKES'
export const ADD_DISLIKE = 'ADD_DISLIKE'
export const ADD_INPUT = 'ADD_INPUT'

export const ADD_COMMENT = 'ADD_COMMENT'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

export const LOAD_COMMENTS = 'LOAD_COMMENTS'
export const DISPLAY_LOADER_ON = 'DISPLAY_LOADER_ON'
export const DISPLAY_LOADER_OFF = 'DISPLAY_LOADER_OFF'

export const ERROR_DISPLAY_ON = 'ERROR_DIPLAY_ON'
export const ERROR_DISPLAY_OFF = 'ERROR_DIPLAY_OFF'